version: "3.8"
services:
  nfs:
    build: .
    image: vimagick/nfs
    ports:
      - "2049:2049"
    volumes:
      - ./data:/data
    environment:
      - EXPORT_PATH=/data
    restart: unless-stopped
