squid:
  image: easypi/squid-arm
  ports:
    - "3128:3128/tcp"
    - "3130:3130/udp"
  volumes:
    - ./data/squid.conf:/etc/squid/squid.conf
  ulimits:
    nofile:
      soft: 65536
      hard: 65536
  restart: unless-stopped
