version: "3.8"
services:
  prometheus:
    image: prom/prometheus:v2.31.1
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/var/lib/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    volumes:
      - ./data/etc:/etc/prometheus
      - ./data/var:/var/lib/prometheus
    restart: unless-stopped
