version: "3.8"

services:

  strapi:
    image: strapi/strapi:3.6.0-alpine
    ports:
      - "1337:1337"
    volumes:
      - ./data/strapi:/srv/app
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - DATABASE_NAME=strapi
    restart: unless-stopped

  postgres:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=strapi
      - POSTGRES_DB=strapi
    restart: unless-stopped
