version: "3.7"
services:
  pihole:
    image: pihole/pihole:release-v4.3.4-armhf
    ports:
      - "53:53/udp"
      - "80:80/tcp"
    volumes:
      - ./data/pihole:/etc/pihole
      - ./data/dnsmasq.d:/etc/dnsmasq.d
    environment:
      - TZ=Asia/Shanghai
      - WEBPASSWORD=******
    restart: unless-stopped
