version: '3.7'

services:

  openmeetings:
    image: apache/openmeetings:min-5.0.0-M3
    ports:
      - "5443:5443"
    volumes:
      - ./data/omdata:/opt/omdata
    environment:
      - OM_KURENTO_WS_URL=ws://kurento:8888/kurento
      - OM_DB_HOST=mysql
      - OM_DB_USER=root
      - OM_DB_PASS=root
      - OM_DB_NAME=openmeetings
      - OM_USER=admin
      - OM_PASS=admin
    restart: unless-stopped

  kurento:
    image: kurento/kurento-media-server
    ports:
      - "8888:8888"
    restart: unless-stopped
  
  mysql:
    image: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=openmeetings
    restart: unless-stopped
